### ISSUE TITLE
chore: init directus

### ISSUE THREAD

**Issue by sdkaraarslan** [samicodesit/hospitality-travel-rotterdam#3]
- [Here is the docs for self-hosted Directus installation](https://docs.directus.io/self-hosted/quickstart.html)
- Example docker-compose:
```yaml
---
version: '3'
services:
  directus:
    user: root
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
      - ./directus/database:/directus/database
    env_file: directus/.env
```
- Create a ``directus`` folder and inside it, create ``uploads``, ``extensions`` and ``database`` folders.
- Create a .env inside directus folder. For example:
```env
KEY='bc75c62a-f23f-43f5-b0fd-44b22ef1362d'
SECRET='930e1e2e-86c7-449f-8847-656715809450'

DB_CLIENT='sqlite3'
DB_FILENAME='./database/database.sqlite'

ADMIN_EMAIL='info@example.com'
ADMIN_PASSWORD='Example1234!'

EMAIL_VERIFY_SETUP=false

CORS_ENABLED=true
CORS_ORIGIN=http://localhost:3000

PASSWORD_RESET_URL_ALLOW_LIST=http://localhost:3000/auth/reset-password
USER_INVITE_URL_ALLOW_LIST=http://localhost:3000/auth/complete-registration
PUBLIC_URL=http://localhost:3000
```
- Then run ``docker compose up -d directus``
